RULE_LISTS = 'RULE_LISTS'
CUSTOM_SIGNALS = 'CUSTOM_SIGNALS'
REQUEST_RULES = 'REQUEST_RULES'
SITE_RULES = 'SITE_RULES'
SIGNAL_RULES = 'SIGNAL_RULES'
TEMPLATED_RULES = 'TEMPLATED_RULES'
CUSTOM_ALERTS = 'CUSTOM_ALERTS'
SITE_MEMBERS = 'SITE_MEMBERS'
INTEGRATIONS = 'INTEGRATIONS'
ADVANCED_RULES = 'ADVANCED_RULES'

CATEGORIES = [
    RULE_LISTS,
    CUSTOM_SIGNALS,
    REQUEST_RULES,
    SITE_RULES,
    SIGNAL_RULES,
    TEMPLATED_RULES,
    CUSTOM_ALERTS,
    SITE_MEMBERS,
    INTEGRATIONS,
    ADVANCED_RULES
]

VALID_ROLES = [
    'observer',
    'user',
    'admin',
    'owner'
]